### ISSUE TITLE
Problem bootstrapping on Fedora 22?

### ISSUE THREAD

**Issue by verdurin** [hpcugent/easybuild-easyconfigs#1891]
I've tried bootstrapping EB on three different Fedora 22 machines and have seen the same problem each time, using the script shown in the documentation:

```
easybuild-bootstrap.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 30044  100 30044    0     0  70086      0 --:--:-- --:--:-- --:--:-- 70196
[[INFO]] Found module command 'lmod' (Lmod), so using it.
[[INFO]]

+++ STAGE 0: installing distribute via included (patched) distribute_setup.py...


Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.34.tar.gz
Extracting in /tmp/tmpc9B65S
Now working in /tmp/tmpc9B65S/distribute-0.6.34
Installing Distribute
Something went wrong during the installation.
See the error message above.
[[ERROR]] Installing distribute which should deliver easy_install failed?
Lmod has detected the following error:  The following module(s) are unknown: "EasyBuild"

   Please check the spelling or version number. Also try "module spider ..."
```

**Comment by verdurin** [comment]
Running bootstrap_eb.py with debug enabled:

```
+++ STAGE 0: installing distribute via included (patched) distribute_setup.py...


[[DEBUG]] preparing environment...
[[DEBUG]] Preparing for path /tmp/tmpVO2BPl
[[DEBUG]] os.environ['PYTHONPATH'] after reset:
[[DEBUG]] $EASYBUILD_MODULES_TOOL set to Lmod
[[DEBUG]] distribute_setup.__file__: /tmp/tmpVO2BPl/distribute_setup.py
Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.34.tar.gz
Extracting in /tmp/tmph_Id7d
Now working in /tmp/tmph_Id7d/distribute-0.6.34
Installing Distribute
Before install bootstrap.
Scanning installed packages
Setuptools installation detected at /usr/lib/python2.7/site-packages
Not patching, --root or --prefix is installing Distribute in another location
Traceback (most recent call last):
  File "setup.py", line 248, in <module>
    scripts = scripts,
  File "/usr/lib64/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/tmp/tmph_Id7d/distribute-0.6.34/setuptools/dist.py", line 225, in __init__
    _Distribution.__init__(self,attrs)
  File "/usr/lib64/python2.7/distutils/dist.py", line 287, in __init__
    self.finalize_options()
  File "/tmp/tmph_Id7d/distribute-0.6.34/setuptools/dist.py", line 257, in finalize_options
    ep.require(installer=self.fetch_build_egg)
  File "/tmp/tmph_Id7d/distribute-0.6.34/pkg_resources.py", line 2025, in require
    working_set.resolve(self.dist.requires(self.extras),env,installer))
  File "/tmp/tmph_Id7d/distribute-0.6.34/pkg_resources.py", line 2235, in requires
    dm = self._dep_map
  File "/tmp/tmph_Id7d/distribute-0.6.34/pkg_resources.py", line 2464, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/tmp/tmph_Id7d/distribute-0.6.34/pkg_resources.py", line 2497, in _compute_dependencies
    common = frozenset(reqs_for_extra(None))
  File "/tmp/tmph_Id7d/distribute-0.6.34/pkg_resources.py", line 2494, in reqs_for_extra
    if req.marker_fn(override={'extra':extra}):
  File "/tmp/tmph_Id7d/distribute-0.6.34/_markerlib/markers.py", line 109, in marker_fn
    return eval(compiled_marker, environment)
  File "<environment marker>", line 1, in <module>
NameError: name 'sys_platform' is not defined
Something went wrong during the installation.
See the error message above.
[[ERROR]] Installing distribute which should deliver easy_install failed?
```

**Comment by boegel** [comment]
Similar issues have been reported before, but we never got to the bottom of this.

Can you take a look at https://github.com/hpcugent/easybuild-framework/issues/1099#issuecomment-64903116 (go down from there)?

**Comment by boegel** [comment]
Also, this is the wrong repository for reporting this kind of problem, so consider moving this to https://github.com/hpcugent/easybuild-framework

**Comment by verdurin** [comment]
@boegel - apologies.  I'll close this and look at the issue referred to above.
