### ISSUE TITLE
test_dep_graph unit test isn't properly protected

### ISSUE THREAD

**Issue by geimer** [hpcugent/easybuild-easyconfigs#3681]
When I run the easyconfigs unit test suite on my test machine, I get the following error:
```
ERROR: test_dep_graph (test.easyconfigs.easyconfigs.EasyConfigTest)
Unit test that builds a full dependency graph.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/geimer/Projects/EasyBuild/easybuild-easyconfigs/test/easyconfigs/easyconfigs.py", line 131, in test_dep_graph
    dep_graph(fn, self.ordered_specs)
  File "/home/geimer/Projects/EasyBuild/easybuild-framework/easybuild/tools/utilities.py", line 145, in error
    raise EasyBuildError("ImportError: %s", msg)
EasyBuildError: "ImportError: No module named pygraph.classes.digraph; required module 'pygraph.classes.digraph' is not available (provided by Python package python-graph-core, available from https://pypi.python.org/pypi/python-graph-core)"
```
Like many other tests, in framework for example, this test should probably be skipped if the required module isn't available.

**Comment by boegel** [comment]
Hmm, the whole point of this test is to make sure that all required dependencies are available for all easyconfig, not so much to test `dep_graph`...

So, rather than just skipping the test, we should look into verifying that same aspect without `dep_graph` instead.
