### ISSUE TITLE
IPython easyconfig fails during iptest due to broken X11 forwarding

### ISSUE THREAD

**Issue by dominikborkowski** [hpcugent/easybuild-easyconfigs#4392]
This issue is to track an odd problem encountered with IPython-5.1.0-foss-2016b-Python-2.7.12.eb and consequent solution.

IPython install was failing with a vague error:
"Sanity check failed: sanity check command iptest exited with code 1"

Digging through the layers of logs I've found the following problem, during one of the iptest steps:

```
== 2017-03-23 12:16:01,145 build_log.py:147 ERROR EasyBuild crashed with an error (at easybuild/software/shadowfax-westmere/EasyBuild/3.1.2/lib64/python2.6/site-packages/vsc_base-2.5.7-py2.6.egg/vsc/utils/exceptions.py:124 in __init__): Sanity check failed: sanity check command iptest  exited with code 1 (output:
Test group: core
........................................SSSSS....................S.S..............................SSS..................................................................................................................................................................................................................
KeyboardInterrupt

....Alarm clock
.........................................................................................................................S....................................................................................
----------------------------------------------------------------------
Ran 521 tests in 28.768s

OK (SKIP=11)

Test group: extensions
..
----------------------------------------------------------------------
Ran 2 tests in 0.015s

OK

Test group: lib
....E..........................SS..............S....................S.....
======================================================================
ERROR: IPython.lib.tests.test_clipboard.test_clipboard_get
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/apps/easybuild/software/shadowfax-westmere/Python/2.7.12-foss-2016b/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/apps/easybuild/software/shadowfax-westmere/IPython/5.1.0-foss-2016b-Python-2.7.12/lib/python2.7/site-packages/IPython/testing/decorators.py", line 212, in skipper_func
    return f(*args, **kwargs)
  File "/apps/easybuild/software/shadowfax-westmere/IPython/5.1.0-foss-2016b-Python-2.7.12/lib/python2.7/site-packages/IPython/lib/tests/test_clipboard.py", line 14, in test_clipboard_get
    a = get_ipython().hooks.clipboard_get()
  File "/apps/easybuild/software/shadowfax-westmere/IPython/5.1.0-foss-2016b-Python-2.7.12/lib/python2.7/site-packages/IPython/core/hooks.py", line 149, in __call__
    return cmd(*args, **kw)
  File "/apps/easybuild/software/shadowfax-westmere/IPython/5.1.0-foss-2016b-Python-2.7.12/lib/python2.7/site-packages/IPython/core/hooks.py", line 225, in clipboard_get
    text = dispatcher()
  File "/apps/easybuild/software/shadowfax-westmere/IPython/5.1.0-foss-2016b-Python-2.7.12/lib/python2.7/site-packages/IPython/core/hooks.py", line 149, in __call__
    return cmd(*args, **kw)
  File "/apps/easybuild/software/shadowfax-westmere/IPython/5.1.0-foss-2016b-Python-2.7.12/lib/python2.7/site-packages/IPython/lib/clipboard.py", line 61, in tkinter_clipboard_get
    root = Tk()
  File "/apps/easybuild/software/shadowfax-westmere/Python/2.7.12-foss-2016b/lib/python2.7/lib-tk/Tkinter.py", line 1815, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
TclError: couldn't connect to display "localhost:16.0"
```
This seems to have been caused by a broken X11 forwarding, enabled via ssh. As soon as I disabled that, the tests ran fine and IPython could be installed.

**Comment by dominikborkowski** [comment]
Closing the issue, as solution was outlined in the initial request.

**Comment by boegel** [comment]
Thanks for logging this @dominikborkowski!
